// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Property } from "./Property";

export type GeneratorInfo = { 
/**
 * The name of the generator
 */
name: string, 
/**
 * The description of a generator
 */
description: string, 
/**
 * The output language syntax of the generated code if any
 */
syntax: string | null, 
/**
 * The extensions supported by the generator if any
 */
extensions: Array<string> | null, 
/**
 * Defines extra properties defined by the generator if any
 */
properties: Array<Property> | null, 
/**
 * Whether the generator result should/can be saved
 */
saveable: boolean, };
