// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyValue } from "./PropertyValue";

export type GeneratorOptions = { fontSize: number, fontFamily: string, extra: { [key in string]?: PropertyValue }, };
