// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyType } from "./PropertyType";
import type { PropertyValue } from "./PropertyValue";

export type Property = { name: string, kind: PropertyType, value: PropertyValue, description: string, default: PropertyValue | null, min: PropertyValue | null, max: PropertyValue | null, };
