// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneratorEvent = { "kind": "started" } | { "kind": "cancelled" } | { "kind": "progress", total: number, current: number, };
