// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyValue } from "./PropertyValue";

export type TemplateUserData = { font_size: number, font_family: string, theme_name: string, syntax_name: string, code: string, props: { [key in string]?: PropertyValue }, };
