// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyInfo } from "./PropertyInfo";

export type TemplateInfo = { name: string, content: string, description: string, extra_properties: Array<PropertyInfo>, };
